/** Rain API occupation codes (SOC-style + special codes). Send code string as `occupation`. */
export const RAIN_OCCUPATION_OPTIONS: { value: string; label: string }[] = [
  { value: '11-1011', label: 'Chief Executives' },
  { value: '11-3031', label: 'Financial Managers' },
  { value: '11-9021', label: 'Construction Managers' },
  { value: '11-9111', label: 'Medical and Health Services Managers' },
  { value: '13-2011', label: 'Accountants and Auditors' },
  { value: '13-2051', label: 'Financial Analysts' },
  { value: '13-2082', label: 'Tax Preparers' },
  { value: '13-1021', label: 'Buyers and Purchasing Agents' },
  { value: '13-2072', label: 'Loan Officers' },
  { value: '15-1121', label: 'Computer Systems Analysts' },
  { value: '15-1132', label: 'Software Developers' },
  { value: '15-1142', label: 'Network and Computer Systems Administrators' },
  { value: '17-2051', label: 'Civil Engineers' },
  { value: '17-2141', label: 'Mechanical Engineers' },
  { value: '17-3021', label: 'Aerospace Engineering Technicians' },
  { value: '29-1021', label: 'Dentists' },
  { value: '29-1067', label: 'Surgeons' },
  { value: '29-1141', label: 'Registered Nurses' },
  { value: '29-2041', label: 'Paramedics' },
  { value: '23-1011', label: 'Lawyers' },
  { value: '23-1023', label: 'Judges' },
  { value: '23-2011', label: 'Paralegals and Legal Assistants' },
  { value: '27-1011', label: 'Art Directors' },
  { value: '27-2012', label: 'Producers and Directors' },
  { value: '27-2021', label: 'Athletes and Sports Competitors' },
  { value: '27-3043', label: 'Writers and Authors' },
  { value: '49-3011', label: 'Aircraft Mechanics' },
  { value: '49-3023', label: 'Automotive Service Technicians' },
  { value: '49-9021', label: 'Heating, AC, and Refrigeration Mechanics' },
  { value: 'SELFEMP', label: 'Self-Employed' },
  { value: 'OTHERXX', label: 'Other' },
  { value: 'UNEMPLO', label: 'Unemployed' },
  { value: 'STUDENT', label: 'Student' },
  { value: 'RETIRED', label: 'Retired' },
];
