name: Deploy mobile QA

jobs:
  android_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: preview
  ios_build:
    name: Build iOS
    type: build
    params:
      platform: ios
      profile: preview
