name: Deploy mobile QA

# Disabled - workflow will not trigger
# on:
#   push:
#     branches: ['qa']

jobs:
  android_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: preview
  ios_build:
    name: Build iOS
    type: build
    params:
      platform: ios
      profile: preview
