name: Deploy QA

on:
  push:
    branches: ['qa']

jobs:
  deploy:
    name: Deploy QA
    environment: preview
    steps:
      - uses: eas/checkout
      - uses: eas/use_npm_token
      - name: Setup pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Install EAS CLI
        run: pnpm add -g eas-cli
      - name: Build
        run: npx expo export --platform web
      - name: Publish
        run: eas deploy --alias qa
