name: Deploy

on:
  push:
    branches: ['master']

jobs:
  deploy:
    name: Deploy
    environment: production
    steps:
      - uses: eas/checkout
      - uses: eas/use_npm_token
      - name: Install dependencies
        run: pnpm install
      - name: Install EAS CLI
        run: pnpm add -g eas-cli
      - name: Build
        run: npx expo export --platform web
      - name: Publish
        run: eas deploy --prod
