name: Lint & Format

on:
  push:
    branches: [master, qa]
  pull_request:
    branches: [master, qa]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint with Expo
        run: npm run lint

      - name: Check Prettier formatting
        run: npx prettier --check "**/*.{ts,tsx,js,jsx,json}" --ignore-path .eslintignore

      - name: TypeScript compilation check
        run: npx tsc --noEmit